export const Products = [
    {
        id:1,
        price:599,
        brand:"Roadster",
        gender:"Men",
        size:"XL",
        qty:1,
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657114639/roc8Challenge/Men_T-shirt-1_Roadster_tuhbru.jpg"
    },
    {
        id:2,
        price:499,
        brand:"Roadster",
        gender:"Men",
        size:"S",
        qty:1,
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657114654/roc8Challenge/Men_T-shirt-2_Roadster_ekgdgk.jpg"
    },
    {
        id:3,
        price:449,
        brand:"Roadster",
        gender:"Men",
        size:"M",
        qty:1,
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657114664/roc8Challenge/Men_T-shirt-3_Roadster_hukgse.jpg"
    },
    {
        id:4,
        price:549,
        brand:"HRX",
        gender:"Men",
        size:"XL",
        qty:1,
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657114674/roc8Challenge/Men_T-shirt-4_HRX_gznhhy.jpg"
    },
    {
        id:5,
        price:799,
        brand:"HRX",
        gender:"Men",
        size:"XL",
        qty:1,
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657114683/roc8Challenge/Men_T-shirt-5_HRX_wctx0a.webp"
    },
    {
        id:7,
        price:649,
        brand:"WRONG",
        gender:"Men",
        size:"L",
        qty:1,
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657114720/roc8Challenge/Men_T-shirt-7_WRONG_ff7as1.webp"
    },
    {
        id:8,
        price:669,
        brand:"WRONG",
        gender:"Men",
        size:"S",
        qty:1,
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657114730/roc8Challenge/Men_T-shirt-8_WRONG_tqwkzs.webp"
    },
    {
        id:9,
        price:679,
        brand:"WRONG",
        gender:"Men",
        size:"M",
        qty:1,
        img:"https://res.cloudinary.com/aprabhat/image/upload/v1657114738/roc8Challenge/Men_T-shirt-9_WRONG_cm2imi.webp"
    },
]